### ISSUE TITLE
Accessing External Interface method from Angular Services 

### ISSUE THREAD

**Issue by derMani** [w11k/w11k-flash#4]
I am encountering a (imho) more complex problem and I would like to discuss it.

Our Flash (RTMP) component provides a lot methods for interacting with other users and components. 

W11k-flash offers controller based access to the flash methods of the ExternalInterface. But what could we do to access those methods, if we leave the controller/state? 

Brief example: A Flash music player. In the "actual state", the Controller shows all the UI components and provides a direct access to the AS ExternalInterface via w11k-flash.  After changing the state of the application, we are in a new controller and we lose the context of the previous scope. 
But how can we change the track or volume now (for example in a simplified side menu widget )? Would that widget have to implement the same methods in another controller again? 
Can we somehow provide an angular service, which can be used in every controller / directive and provides access to the ExternalInterface?

I am trying to reduce the complexity of the controllers in an "Angular way". 

Best regards
Rolf

**Comment by pburgmer** [comment]
Hi Rolf,

Thank you for your ticket and usage of w11k-flash.

Including a flash movie into your application is a ui contribution and therefore should be done via a directive in Angular. To be a encapsulated component w11k-flash does not rely on a service or specific variables on outer scope (something like global variables). That's the reason why we are passing the configuration from the controller to the directive.
You're right, if your scope/controller gets destroyed, you will lost the reference to the flash instance. But the flash movie will be removed from the ui too.

If you need access to your flash from the hole application, I would prefer something like this:
Avoid Flash re-instantiation (due to performance), so place w11k-flash somewhere outside of your routing on your main template. Write a small controller, only responsible to manage the flash (I call it FlashCtrl from now on).
Use a Controller-Service-Event architecture: Create a Service (FlashService) exposing some methods to control your Flash. In your different controllers use your FlashService to trigger changes.
In your FlashCtrl register an event listener on $rootScope. The service methods emit an event on $rootScope for each call. By listening to this events the FlashCtrl is able to delegate the call to flash instance.

This approach seems to be over-engineered. But my advice is: do not expose the flash instance via a service. By doing so you have to take care of cleaning up and will probably create a memory leak.

If you have any questions, feel free to ask.

Regards,
Philipp

**Comment by derMani** [comment]
Hey Philipp,

sorry, my email notifications totally failed me here. Thanks for your detailed answer. 

I agree, your approach seems to be slightly over-engineered. I helped myself in the meantime with something similar which involved a lot of event magic. So I did basically pretty much the same you as you suggested. 

It still feels like some kind of workaround :) But I think it is ok for me at the given moment. 

Regards from Osnabrück
Rolf
